In [11]:
import numpy as np
from util import preprocess, create_co_matrix, cos_similarity, ppmi,most_similar

In [12]:
text ="I have a pen. I have a apple. umm, apple pen. I have a pen. I have a pineapple. umm, pineapple pen."

In [13]:
corpus, word_to_id, id_to_word = preprocess(text)

In [5]:
corpus

array([0, 1, 2, 3, 4])

In [6]:
word_to_id

{'i': 0, 'have': 1, 'a': 2, 'pen': 3, '.': 4}

In [7]:
id_to_word

{0: 'i', 1: 'have', 2: 'a', 3: 'pen', 4: '.'}

In [14]:
vocab_size = len(word_to_id)

In [15]:
C = create_co_matrix(corpus, vocab_size)
W= ppmi(C)

In [16]:
np.set_printoptions(precision=3)

In [17]:
print(C)

[[0 4 0 0 3 0 0 0]
 [4 0 4 0 0 0 0 0]
 [0 4 0 2 0 1 0 1]
 [0 0 2 0 4 1 0 1]
 [3 0 0 4 0 1 2 1]
 [0 0 1 1 1 0 1 0]
 [0 0 0 0 2 1 0 1]
 [0 0 1 1 1 0 1 0]]


In [18]:
print(W)

[[0.    1.948 0.    0.    1.073 0.    0.    0.   ]
 [1.948 0.    1.755 0.    0.    0.    0.    0.   ]
 [0.    1.755 0.    0.755 0.    0.755 0.    0.755]
 [0.    0.    0.755 0.    1.295 0.755 0.    0.755]
 [1.073 0.    0.    1.295 0.    0.295 1.295 0.295]
 [0.    0.    0.755 0.755 0.295 0.    1.755 0.   ]
 [0.    0.    0.    0.    1.295 1.755 0.    1.755]
 [0.    0.    0.755 0.755 0.295 0.    1.755 0.   ]]


In [19]:
c0 = C[word_to_id['apple']]
c1 = C[word_to_id['pineapple']]

In [20]:
print(cos_similarity(c0,c1))

0.9999999900000001


In [21]:
most_similar('apple', word_to_id, id_to_word, C, top=5)


[query] apple
 pineapple: 0.9999999900000001
 pen: 0.6396021445051843
 .: 0.5388159024185033
 umm,: 0.4082482867559549
 have: 0.3535533882005068
